"use client";

/**
 * Resumes page — P20
 * List of tailored resumes generated by Aarya.
 */

import Link from "next/link";
import { useEffect, useState } from "react";
import { Download, FileText, RefreshCw } from "lucide-react";
import {
  listTailoredResumes,
  openTailoredDownload,
  type TailoredResumeRow,
} from "@/lib/api/tailored";
import { Badge, Button, Card, CardBody, EmptyState } from "@/components/ui";
import { AppShell } from "@/components/layout/AppShell";

const STATUS_META: Record<
  string,
  { tone: "muted" | "strong" | "accent"; label: string }
> = {
  pending:    { tone: "muted",   label: "Processing…" },
  generating: { tone: "muted",   label: "Generating…" },
  ready:      { tone: "accent",  label: "Ready"        },
  error:      { tone: "strong",  label: "Failed"       },
};

export default function ResumesPage() {
  const [rows, setRows]       = useState<TailoredResumeRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError]     = useState<string | null>(null);

  function load() {
    setLoading(true);
    listTailoredResumes()
      .then((r) => { setRows(r); setLoading(false); })
      .catch((e) => { setError(e.message); setLoading(false); });
  }

  useEffect(() => { load(); }, []);

  return (
    <AppShell
      title="Tailored resumes"
      activeNav="resumes"
      action={
        <Button
          variant="ghost"
          size="sm"
          onClick={load}
          loading={loading}
          leftIcon={<RefreshCw className="h-3.5 w-3.5" strokeWidth={1.5} />}
        >
          Refresh
        </Button>
      }
    >
      <div className="space-y-3">

        {error && (
          <div className="text-destructive text-small bg-destructive-bg rounded-md px-4 py-3">
            {error}
          </div>
        )}

        {/* Skeleton */}
        {loading && !error && Array.from({ length: 3 }).map((_, i) => (
          <div key={i} className="h-16 rounded-lg bg-ink-100 animate-skeleton" />
        ))}

        {/* Empty */}
        {!loading && !error && rows.length === 0 && (
          <EmptyState
            icon={<FileText strokeWidth={1.5} />}
            title="No tailored resumes yet"
            description='Use the "Tailor" button on any job card in your match feed to generate a role-specific resume.'
            action={
              <Link href="/dashboard">
                <Button variant="secondary" size="sm">
                  Go to matches
                </Button>
              </Link>
            }
          />
        )}

        {/* List */}
        {!loading && rows.map((r) => {
          const meta = STATUS_META[r.status] ?? { tone: "muted" as const, label: r.status };
          return (
            <Card key={r.id} className="hover:shadow-2 transition-shadow">
              <CardBody>
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-md bg-ink-100 flex items-center justify-center shrink-0">
                    <FileText className="h-4 w-4 text-ink-500" strokeWidth={1.5} />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-body font-medium text-ink-900 truncate">
                      {r.job_title ?? "Tailored resume"}
                    </p>
                    <div className="flex items-center gap-2 mt-0.5">
                      <Badge tone={meta.tone}>{meta.label}</Badge>
                      {r.template && (
                        <span className="text-micro text-ink-500 capitalize">
                          {r.template} template
                        </span>
                      )}
                    </div>
                  </div>
                  {r.status === "ready" && (
                    <Button
                      variant="secondary"
                      size="sm"
                      onClick={() => openTailoredDownload(r.id)}
                      leftIcon={<Download className="h-3.5 w-3.5" strokeWidth={1.5} />}
                    >
                      Download
                    </Button>
                  )}
                </div>
              </CardBody>
            </Card>
          );
        })}
      </div>
    </AppShell>
  );
}
