#!/usr/bin/env python3
"""
Write app/.env.local and api/.env Supabase keys from scripts/supabase-credentials.env.

Usage:
  cp scripts/supabase-credentials.env.example scripts/supabase-credentials.env
  # edit supabase-credentials.env with real values
  python3 scripts/configure_supabase.py
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
CREDS_FILE = ROOT / "scripts" / "supabase-credentials.env"
APP_ENV = ROOT / "app" / ".env.local"
API_ENV = ROOT / "api" / ".env"


def load_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        print(f"Missing {path}")
        print("Copy scripts/supabase-credentials.env.example → scripts/supabase-credentials.env")
        sys.exit(1)

    out: dict[str, str] = {}
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, value = line.partition("=")
        out[key.strip()] = value.strip().strip('"').strip("'")
    return out


def require(creds: dict[str, str], *keys: str) -> None:
    missing = [k for k in keys if not creds.get(k) or "your-" in creds.get(k, "")]
    if missing:
        print("Missing or placeholder values for:", ", ".join(missing))
        sys.exit(1)


def normalize_supabase_url(raw_url: str) -> str:
    """
    Accept either:
      - https://<ref>.supabase.co
      - https://<ref>.supabase.co/rest/v1
    and always return base origin.
    """
    parsed = urlparse(raw_url.strip())
    if not parsed.scheme or not parsed.netloc:
        print("Invalid SUPABASE_URL:", raw_url)
        sys.exit(1)
    return f"{parsed.scheme}://{parsed.netloc}"


def build_database_url(creds: dict[str, str]) -> str:
    ref = creds["SUPABASE_PROJECT_REF"]
    password = creds["SUPABASE_DB_PASSWORD"]
    host = creds.get("SUPABASE_DB_HOST") or f"db.{ref}.supabase.co"
    # Direct DB connection is the most reliable default for local development.
    user = creds.get("SUPABASE_DB_USER") or "postgres"
    port = creds.get("SUPABASE_DB_PORT") or "5432"
    return f"postgresql+asyncpg://{user}:{password}@{host}:{port}/postgres?sslmode=require"


def upsert_env_lines(path: Path, updates: dict[str, str]) -> None:
    lines: list[str] = []
    if path.exists():
        lines = path.read_text().splitlines()

    seen: set[str] = set()
    new_lines: list[str] = []
    for line in lines:
        if "=" in line and not line.strip().startswith("#"):
            key = line.split("=", 1)[0].strip()
            if key in updates:
                new_lines.append(f"{key}={updates[key]}")
                seen.add(key)
                continue
        new_lines.append(line)

    for key, value in updates.items():
        if key not in seen:
            new_lines.append(f"{key}={value}")

    path.write_text("\n".join(new_lines) + "\n")


def write_app_env(creds: dict[str, str]) -> None:
    app_url = creds.get("APP_URL", "http://localhost:3001")
    api_url = creds.get("API_URL", "http://localhost:8000")
    updates = {
        "NEXT_PUBLIC_SUPABASE_URL": creds["SUPABASE_URL"],
        "NEXT_PUBLIC_SUPABASE_ANON_KEY": creds["SUPABASE_ANON_KEY"],
        "NEXT_PUBLIC_API_URL": api_url,
    }
    if APP_ENV.exists():
        upsert_env_lines(APP_ENV, updates)
    else:
        template = (ROOT / "app" / ".env.example").read_text()
        APP_ENV.write_text(template)
        upsert_env_lines(APP_ENV, updates)
    print(f"Updated {APP_ENV}")


def write_api_env(creds: dict[str, str]) -> None:
    origins = creds.get("ALLOWED_ORIGINS", "http://localhost:3001,http://localhost:3000")
    updates = {
        "ENVIRONMENT": "development",
        "DATABASE_URL": build_database_url(creds),
        "SUPABASE_URL": creds["SUPABASE_URL"],
        "SUPABASE_SERVICE_KEY": creds["SUPABASE_SERVICE_ROLE_KEY"],
        "ALLOWED_ORIGINS": origins,
    }
    if not API_ENV.exists():
        template = (ROOT / "api" / ".env.example").read_text()
        API_ENV.write_text(template)
    upsert_env_lines(API_ENV, updates)
    print(f"Updated {API_ENV}")


def write_supabase_config(creds: dict[str, str]) -> None:
    config_dir = ROOT / "supabase"
    config_dir.mkdir(exist_ok=True)
    config_path = config_dir / "config.toml"
    ref = creds["SUPABASE_PROJECT_REF"]
    content = f'''# Generated by scripts/configure_supabase.py — do not commit secrets here
project_id = "{ref}"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323
'''
    config_path.write_text(content)
    print(f"Wrote {config_path} (project_id={ref})")


def main() -> None:
    creds = load_env_file(CREDS_FILE)
    require(
        creds,
        "SUPABASE_PROJECT_REF",
        "SUPABASE_URL",
        "SUPABASE_ANON_KEY",
        "SUPABASE_SERVICE_ROLE_KEY",
        "SUPABASE_DB_PASSWORD",
    )
    creds["SUPABASE_URL"] = normalize_supabase_url(creds["SUPABASE_URL"])
    write_app_env(creds)
    write_api_env(creds)
    write_supabase_config(creds)
    print("\nNext steps:")
    print("  1. supabase login && supabase link --project-ref", creds["SUPABASE_PROJECT_REF"])
    print("  2. supabase db push")
    print("  3. python3 scripts/verify_supabase_connection.py")
    print("  4. In Supabase Dashboard → Auth → URL config:")
    print(f"       Site URL: {creds.get('APP_URL', 'http://localhost:3001')}")
    print(f"       Redirect: {creds.get('APP_URL', 'http://localhost:3001')}/auth/callback")


if __name__ == "__main__":
    main()
