"""
Build the bundled canonical skills vocabulary (HIR — skills.py expansion).

Emits src/hireloop_api/data/skills_vocab.json:
  { "skills":  [<display label>, ...],     # ~2000 curated, deduped
    "aliases": { "<variant>": "<canonical display>", ... } }

skills.py loads this once at import. Re-run after editing the category lists:
    cd api && uv run python scripts/build_skills_vocab.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path

# ── Canonical skills, grouped by domain (display labels) ───────────────────────
# Broad, India-relevant coverage across tech + business functions. Curated rather
# than scraped so every entry is a real, matchable skill (no JD fluff).

LANGUAGES = [
    "Python",
    "Java",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "C",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "Objective-C",
    "Dart",
    "R",
    "MATLAB",
    "Perl",
    "Haskell",
    "Elixir",
    "Erlang",
    "Clojure",
    "F#",
    "Groovy",
    "Lua",
    "Julia",
    "Bash",
    "Shell Scripting",
    "PowerShell",
    "SQL",
    "PL/SQL",
    "T-SQL",
    "VBA",
    "COBOL",
    "Fortran",
    "Assembly",
    "Solidity",
    "Visual Basic",
    "Delphi",
    "Apex",
    "ABAP",
    "GDScript",
    "Zig",
    "OCaml",
    "Scheme",
    "Racket",
    "Crystal",
]

FRONTEND = [
    "React",
    "Angular",
    "Vue.js",
    "Svelte",
    "Next.js",
    "Nuxt.js",
    "Remix",
    "Gatsby",
    "SvelteKit",
    "Astro",
    "Redux",
    "MobX",
    "Zustand",
    "Recoil",
    "React Query",
    "RxJS",
    "jQuery",
    "Backbone.js",
    "Ember.js",
    "Alpine.js",
    "HTML",
    "HTML5",
    "CSS",
    "CSS3",
    "Sass",
    "SCSS",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Ant Design",
    "Styled Components",
    "Emotion",
    "PostCSS",
    "Webpack",
    "Vite",
    "Rollup",
    "Parcel",
    "esbuild",
    "Babel",
    "Storybook",
    "Web Components",
    "Progressive Web Apps",
    "WebAssembly",
    "WebGL",
    "Three.js",
    "D3.js",
    "Chart.js",
    "Framer Motion",
    "GSAP",
    "Responsive Design",
    "Cross-Browser Compatibility",
    "Web Accessibility",
    "WCAG",
    "Web Performance Optimization",
    "Core Web Vitals",
    "SPA",
    "SSR",
    "Server Components",
    "Micro Frontends",
    "Figma to Code",
    "Radix UI",
    "shadcn/ui",
]

BACKEND = [
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Koa",
    "Deno",
    "Bun",
    "Django",
    "Flask",
    "FastAPI",
    "Tornado",
    "Pyramid",
    "Spring",
    "Spring Boot",
    "Spring MVC",
    "Spring Security",
    "Spring Cloud",
    "Hibernate",
    "Quarkus",
    "Micronaut",
    "Ruby on Rails",
    "Sinatra",
    "Laravel",
    "Symfony",
    "CodeIgniter",
    "ASP.NET",
    "ASP.NET Core",
    ".NET",
    ".NET Core",
    "Entity Framework",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Phoenix",
    "Play Framework",
    "Vert.x",
    "REST APIs",
    "GraphQL",
    "gRPC",
    "WebSockets",
    "SOAP",
    "OpenAPI",
    "Swagger",
    "Microservices",
    "Monolith Architecture",
    "Serverless",
    "Event-Driven Architecture",
    "Message Queues",
    "API Gateway",
    "API Design",
    "Webhooks",
    "OAuth",
    "OAuth2",
    "OpenID Connect",
    "JWT",
    "SAML",
    "Session Management",
    "Rate Limiting",
    "Caching",
    "Background Jobs",
    "Cron Jobs",
    "Distributed Systems",
    "Domain-Driven Design",
    "CQRS",
    "Event Sourcing",
    "Clean Architecture",
    "Hexagonal Architecture",
    "SOLID Principles",
    "Design Patterns",
]

DATABASES = [
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "SQLite",
    "Oracle Database",
    "SQL Server",
    "Microsoft SQL Server",
    "MongoDB",
    "Cassandra",
    "Couchbase",
    "CouchDB",
    "DynamoDB",
    "Redis",
    "Memcached",
    "Elasticsearch",
    "OpenSearch",
    "Solr",
    "Neo4j",
    "ArangoDB",
    "InfluxDB",
    "TimescaleDB",
    "ClickHouse",
    "Snowflake",
    "Amazon Redshift",
    "Google BigQuery",
    "Azure Synapse",
    "Databricks",
    "Apache Hive",
    "Presto",
    "Trino",
    "DuckDB",
    "CockroachDB",
    "Supabase",
    "Firebase",
    "Firestore",
    "PlanetScale",
    "FaunaDB",
    "RethinkDB",
    "pgvector",
    "Pinecone",
    "Weaviate",
    "Milvus",
    "Qdrant",
    "Chroma",
    "Vector Databases",
    "Database Design",
    "Data Modeling",
    "Query Optimization",
    "Indexing",
    "Database Administration",
    "Replication",
    "Sharding",
    "ACID Transactions",
    "NoSQL",
    "OLAP",
    "OLTP",
    "Database Migration",
    "ORM",
    "Connection Pooling",
]

CLOUD = [
    "AWS",
    "Amazon EC2",
    "AWS Lambda",
    "Amazon S3",
    "Amazon RDS",
    "Amazon ECS",
    "Amazon EKS",
    "AWS Fargate",
    "Amazon CloudFront",
    "Amazon Route 53",
    "AWS CloudFormation",
    "AWS IAM",
    "Amazon SQS",
    "Amazon SNS",
    "Amazon DynamoDB",
    "AWS Step Functions",
    "Amazon API Gateway",
    "Amazon CloudWatch",
    "AWS CDK",
    "Amazon Aurora",
    "AWS Glue",
    "Amazon Athena",
    "Amazon Kinesis",
    "Amazon SageMaker",
    "AWS Elastic Beanstalk",
    "Amazon VPC",
    "AWS Secrets Manager",
    "Amazon ElastiCache",
    "Google Cloud Platform",
    "Google Compute Engine",
    "Google Kubernetes Engine",
    "Google Cloud Functions",
    "Google Cloud Run",
    "Google Cloud Storage",
    "Google Cloud Pub/Sub",
    "Google Cloud SQL",
    "Google Cloud Spanner",
    "Google Cloud Dataflow",
    "Vertex AI",
    "Firebase",
    "Microsoft Azure",
    "Azure Virtual Machines",
    "Azure Functions",
    "Azure App Service",
    "Azure Kubernetes Service",
    "Azure Blob Storage",
    "Azure DevOps",
    "Azure SQL Database",
    "Azure Active Directory",
    "Azure Cosmos DB",
    "Azure Data Factory",
    "Azure Synapse",
    "DigitalOcean",
    "Heroku",
    "Vercel",
    "Netlify",
    "Cloudflare",
    "Cloudflare Workers",
    "Linode",
    "Render",
    "Fly.io",
    "Railway",
    "Oracle Cloud",
    "IBM Cloud",
    "Alibaba Cloud",
    "Cloud Architecture",
    "Cloud Migration",
    "Cloud Security",
    "Cloud Cost Optimization",
    "FinOps",
    "Multi-Cloud",
    "Hybrid Cloud",
    "Serverless Architecture",
]

DEVOPS = [
    "Docker",
    "Kubernetes",
    "Helm",
    "Docker Compose",
    "Podman",
    "containerd",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "SaltStack",
    "Packer",
    "Vagrant",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "CircleCI",
    "Travis CI",
    "Argo CD",
    "Flux",
    "Spinnaker",
    "TeamCity",
    "Bamboo",
    "Drone CI",
    "CI/CD",
    "Infrastructure as Code",
    "GitOps",
    "Configuration Management",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "Splunk",
    "ELK Stack",
    "Logstash",
    "Kibana",
    "Fluentd",
    "Jaeger",
    "OpenTelemetry",
    "PagerDuty",
    "Nagios",
    "Zabbix",
    "Sentry",
    "Observability",
    "Monitoring",
    "Alerting",
    "Site Reliability Engineering",
    "SRE",
    "Incident Management",
    "On-Call",
    "Linux",
    "Linux Administration",
    "Unix",
    "Ubuntu",
    "Red Hat",
    "CentOS",
    "Debian",
    "Nginx",
    "Apache HTTP Server",
    "HAProxy",
    "Load Balancing",
    "Reverse Proxy",
    "Service Mesh",
    "Istio",
    "Linkerd",
    "Envoy",
    "Consul",
    "Vault",
    "Networking",
    "TCP/IP",
    "DNS",
    "VPN",
    "Firewalls",
    "CDN",
    "Shell Scripting",
    "System Administration",
    "Capacity Planning",
    "Disaster Recovery",
    "High Availability",
    "Auto Scaling",
    "Blue-Green Deployment",
    "Canary Deployment",
]

DATA_ML = [
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Reinforcement Learning",
    "Generative AI",
    "Large Language Models",
    "Prompt Engineering",
    "RAG",
    "Fine-Tuning",
    "MLOps",
    "LLMOps",
    "Feature Engineering",
    "Model Deployment",
    "Model Monitoring",
    "A/B Testing",
    "Experimentation",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Hugging Face Transformers",
    "spaCy",
    "NLTK",
    "OpenCV",
    "JAX",
    "ONNX",
    "MLflow",
    "Kubeflow",
    "Weights & Biases",
    "DVC",
    "Ray",
    "Optuna",
    "LangChain",
    "LlamaIndex",
    "OpenAI API",
    "Anthropic Claude",
    "Vector Search",
    "Embeddings",
    "Semantic Search",
    "Recommendation Systems",
    "Time Series Analysis",
    "Anomaly Detection",
    "Clustering",
    "Classification",
    "Regression",
    "Dimensionality Reduction",
    "Statistical Modeling",
    "Bayesian Statistics",
    "Hypothesis Testing",
    "Pandas",
    "NumPy",
    "SciPy",
    "Matplotlib",
    "Seaborn",
    "Plotly",
    "Jupyter",
    "Apache Spark",
    "PySpark",
    "Apache Kafka",
    "Apache Airflow",
    "Apache Flink",
    "Apache Beam",
    "dbt",
    "Databricks",
    "Hadoop",
    "MapReduce",
    "Data Engineering",
    "Data Pipelines",
    "ETL",
    "ELT",
    "Data Warehousing",
    "Data Lakes",
    "Data Lakehouse",
    "Stream Processing",
    "Batch Processing",
    "Data Modeling",
    "Data Governance",
    "Data Quality",
    "Master Data Management",
    "Data Analysis",
    "Data Visualization",
    "Business Intelligence",
    "Tableau",
    "Power BI",
    "Looker",
    "Looker Studio",
    "Metabase",
    "Superset",
    "Qlik",
    "Google Analytics",
    "Mixpanel",
    "Amplitude",
    "Excel",
    "Advanced Excel",
    "Google Sheets",
    "Statistics",
    "Predictive Analytics",
    "Data Mining",
    "Big Data",
    "Data Storytelling",
    "Dashboarding",
    "KPI Reporting",
]

MOBILE = [
    "iOS Development",
    "Android Development",
    "Swift",
    "SwiftUI",
    "UIKit",
    "Objective-C",
    "Kotlin",
    "Jetpack Compose",
    "Android SDK",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Cordova",
    "Capacitor",
    "Expo",
    "Mobile App Development",
    "Mobile UI Design",
    "App Store Optimization",
    "Push Notifications",
    "Mobile Testing",
    "Firebase",
    "Core Data",
    "Realm",
    "Mobile Security",
    "Cross-Platform Development",
    "Progressive Web Apps",
    "Kotlin Multiplatform",
    "ARKit",
    "ARCore",
]

TESTING = [
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Test Automation",
    "Test-Driven Development",
    "Behavior-Driven Development",
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Playwright",
    "Selenium",
    "Puppeteer",
    "Vitest",
    "JUnit",
    "TestNG",
    "Mockito",
    "PyTest",
    "unittest",
    "RSpec",
    "Cucumber",
    "Postman",
    "REST Assured",
    "JMeter",
    "Gatling",
    "Load Testing",
    "Performance Testing",
    "Regression Testing",
    "Smoke Testing",
    "QA Automation",
    "Manual Testing",
    "Test Planning",
    "Test Cases",
    "Bug Tracking",
    "Appium",
    "Quality Assurance",
    "Code Coverage",
    "Contract Testing",
    "Chaos Engineering",
]

SECURITY = [
    "Cybersecurity",
    "Application Security",
    "Network Security",
    "Cloud Security",
    "Information Security",
    "Penetration Testing",
    "Ethical Hacking",
    "Vulnerability Assessment",
    "Security Auditing",
    "Threat Modeling",
    "Incident Response",
    "Security Operations",
    "SIEM",
    "SOC",
    "Encryption",
    "Cryptography",
    "PKI",
    "TLS/SSL",
    "Identity and Access Management",
    "Zero Trust",
    "OWASP",
    "Secure Coding",
    "Static Analysis",
    "DAST",
    "SAST",
    "Burp Suite",
    "Metasploit",
    "Nmap",
    "Wireshark",
    "Kali Linux",
    "Firewall Configuration",
    "IDS/IPS",
    "Endpoint Security",
    "DevSecOps",
    "Compliance",
    "GDPR",
    "HIPAA",
    "SOC 2",
    "ISO 27001",
    "PCI DSS",
    "DPDP Act",
    "Risk Assessment",
    "Security Awareness",
    "Malware Analysis",
    "Digital Forensics",
    "Red Teaming",
    "Blue Teaming",
    "Bug Bounty",
    "Container Security",
    "API Security",
    "Data Privacy",
    "Access Control",
]

DESIGN = [
    "UI Design",
    "UX Design",
    "Product Design",
    "Interaction Design",
    "Visual Design",
    "User Research",
    "Usability Testing",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "Information Architecture",
    "User Flows",
    "Journey Mapping",
    "Personas",
    "Design Thinking",
    "Figma",
    "Sketch",
    "Adobe XD",
    "InVision",
    "Framer",
    "Zeplin",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Adobe After Effects",
    "Adobe Premiere Pro",
    "Canva",
    "Affinity Designer",
    "Motion Design",
    "Typography",
    "Color Theory",
    "Branding",
    "Logo Design",
    "Iconography",
    "Illustration",
    "3D Modeling",
    "Blender",
    "Cinema 4D",
    "Accessibility Design",
    "Mobile-First Design",
    "Responsive Design",
    "Design Handoff",
    "Style Guides",
    "Graphic Design",
    "Web Design",
    "Service Design",
    "Conversion-Centered Design",
]

PM_AGILE = [
    "Product Management",
    "Product Strategy",
    "Product Roadmapping",
    "Roadmapping",
    "Product Discovery",
    "Requirements Gathering",
    "User Stories",
    "Backlog Management",
    "Prioritization",
    "Stakeholder Management",
    "Go-to-Market Strategy",
    "Product Analytics",
    "Product-Led Growth",
    "Feature Prioritization",
    "Competitive Analysis",
    "Market Research",
    "Customer Development",
    "Jobs to Be Done",
    "OKRs",
    "KPIs",
    "Product Vision",
    "MVP Development",
    "Agile",
    "Scrum",
    "Kanban",
    "SAFe",
    "Lean",
    "Waterfall",
    "Sprint Planning",
    "Sprint Retrospectives",
    "Daily Standups",
    "Story Pointing",
    "Velocity Tracking",
    "Jira",
    "Confluence",
    "Linear",
    "Asana",
    "Trello",
    "Monday.com",
    "Notion",
    "Aha!",
    "Productboard",
    "Miro",
    "Program Management",
    "Project Management",
    "PMP",
    "Risk Management",
    "Resource Planning",
    "Gantt Charts",
    "Release Management",
    "Cross-Functional Leadership",
    "Technical Program Management",
]

MARKETING = [
    "Digital Marketing",
    "Content Marketing",
    "SEO",
    "Technical SEO",
    "On-Page SEO",
    "Off-Page SEO",
    "Link Building",
    "Keyword Research",
    "SEM",
    "PPC",
    "Google Ads",
    "Meta Ads",
    "Facebook Ads",
    "Instagram Ads",
    "LinkedIn Ads",
    "Twitter Ads",
    "TikTok Ads",
    "Display Advertising",
    "Programmatic Advertising",
    "Retargeting",
    "Performance Marketing",
    "Growth Marketing",
    "Growth Hacking",
    "Email Marketing",
    "Marketing Automation",
    "Lifecycle Marketing",
    "Drip Campaigns",
    "Social Media Marketing",
    "Social Media Management",
    "Community Management",
    "Influencer Marketing",
    "Affiliate Marketing",
    "Brand Marketing",
    "Brand Strategy",
    "Content Strategy",
    "Copywriting",
    "Content Writing",
    "Blogging",
    "Storytelling",
    "Conversion Rate Optimization",
    "Landing Page Optimization",
    "A/B Testing",
    "Marketing Analytics",
    "Google Analytics",
    "Google Tag Manager",
    "GA4",
    "Google Search Console",
    "Ahrefs",
    "SEMrush",
    "Moz",
    "HubSpot",
    "Marketo",
    "Mailchimp",
    "Klaviyo",
    "Salesforce Marketing Cloud",
    "Hootsuite",
    "Buffer",
    "Canva",
    "Webinars",
    "Event Marketing",
    "Product Marketing",
    "Positioning",
    "Messaging",
    "Demand Generation",
    "Lead Generation",
    "Account-Based Marketing",
    "Public Relations",
    "Media Planning",
    "Marketing Strategy",
    "Campaign Management",
    "Video Marketing",
    "YouTube Marketing",
    "Podcast Marketing",
    "Newsletter Growth",
    "Customer Segmentation",
    "Funnel Optimization",
    "Attribution Modeling",
    "WhatsApp Marketing",
]

SALES = [
    "Sales",
    "B2B Sales",
    "B2C Sales",
    "Inside Sales",
    "Field Sales",
    "SaaS Sales",
    "Enterprise Sales",
    "Solution Selling",
    "Consultative Selling",
    "Sales Development",
    "Lead Qualification",
    "Cold Calling",
    "Cold Emailing",
    "Prospecting",
    "Pipeline Management",
    "Account Management",
    "Key Account Management",
    "Sales Operations",
    "Revenue Operations",
    "Sales Enablement",
    "Sales Forecasting",
    "Negotiation",
    "Closing",
    "Upselling",
    "Cross-Selling",
    "Customer Retention",
    "Channel Sales",
    "Partnerships",
    "Business Development",
    "CRM",
    "Salesforce",
    "HubSpot CRM",
    "Zoho CRM",
    "Pipedrive",
    "Outreach",
    "Salesloft",
    "Apollo.io",
    "LinkedIn Sales Navigator",
    "Gong",
    "Territory Management",
    "Quota Attainment",
    "Customer Success",
    "Account Expansion",
    "Relationship Building",
]

FINANCE = [
    "Financial Analysis",
    "Financial Modeling",
    "Financial Planning",
    "FP&A",
    "Budgeting",
    "Forecasting",
    "Accounting",
    "Bookkeeping",
    "Accounts Payable",
    "Accounts Receivable",
    "General Ledger",
    "Reconciliation",
    "Auditing",
    "Internal Audit",
    "Taxation",
    "GST",
    "Income Tax",
    "TDS",
    "Transfer Pricing",
    "Cost Accounting",
    "Management Accounting",
    "Financial Reporting",
    "IFRS",
    "GAAP",
    "Ind AS",
    "Consolidation",
    "Valuation",
    "DCF",
    "Investment Analysis",
    "Equity Research",
    "Portfolio Management",
    "Risk Management",
    "Treasury",
    "Corporate Finance",
    "Mergers and Acquisitions",
    "Private Equity",
    "Venture Capital",
    "Fundraising",
    "Cap Table Management",
    "Unit Economics",
    "Cash Flow Management",
    "Working Capital",
    "Payroll",
    "Compliance",
    "SOX",
    "Tally",
    "QuickBooks",
    "SAP FICO",
    "Oracle Financials",
    "Zoho Books",
    "Excel Modeling",
    "Fintech",
    "Payments",
    "Lending",
    "Underwriting",
    "Credit Analysis",
    "Wealth Management",
    "Insurance",
    "Actuarial Analysis",
    "Blockchain",
    "Cryptocurrency",
    "DeFi",
]

HR = [
    "Recruiting",
    "Technical Recruiting",
    "Talent Acquisition",
    "Sourcing",
    "Candidate Screening",
    "Interviewing",
    "Employer Branding",
    "Onboarding",
    "HR Operations",
    "HRBP",
    "People Operations",
    "Performance Management",
    "Compensation and Benefits",
    "Payroll Management",
    "Employee Engagement",
    "Talent Management",
    "Learning and Development",
    "Workforce Planning",
    "HR Analytics",
    "HRIS",
    "Workday",
    "SAP SuccessFactors",
    "Greenhouse",
    "Lever",
    "BambooHR",
    "Diversity and Inclusion",
    "Employee Relations",
    "Labor Law",
    "Organizational Development",
    "Succession Planning",
    "Change Management",
]

OPS_INDUSTRY = [
    "Operations Management",
    "Supply Chain Management",
    "Logistics",
    "Procurement",
    "Inventory Management",
    "Warehouse Management",
    "Demand Planning",
    "Vendor Management",
    "Process Improvement",
    "Lean Six Sigma",
    "Six Sigma",
    "Kaizen",
    "Quality Control",
    "Quality Management",
    "Manufacturing",
    "Production Planning",
    "ERP",
    "SAP",
    "SAP MM",
    "SAP SD",
    "Oracle ERP",
    "NetSuite",
    "Customer Support",
    "Customer Service",
    "Technical Support",
    "Zendesk",
    "Freshdesk",
    "Intercom",
    "Call Center Operations",
    "E-commerce",
    "Shopify",
    "Magento",
    "WooCommerce",
    "Amazon Seller Central",
    "Marketplace Management",
    "Category Management",
    "Merchandising",
    "Retail",
    "Healthcare",
    "Clinical Research",
    "Pharmacovigilance",
    "Medical Coding",
    "Telecommunications",
    "Automotive",
    "Real Estate",
    "Hospitality",
    "EdTech",
    "Renewable Energy",
    "Oil and Gas",
    "Construction Management",
    "Civil Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "CAD",
    "AutoCAD",
    "SolidWorks",
    "Embedded Systems",
    "IoT",
    "Robotics",
    "PLC Programming",
    "Firmware Development",
]

SOFT_SKILLS = [
    "Communication",
    "Written Communication",
    "Verbal Communication",
    "Presentation Skills",
    "Public Speaking",
    "Active Listening",
    "Storytelling",
    "Leadership",
    "Team Leadership",
    "People Management",
    "Mentoring",
    "Coaching",
    "Delegation",
    "Decision Making",
    "Critical Thinking",
    "Problem Solving",
    "Analytical Thinking",
    "Strategic Thinking",
    "Creativity",
    "Innovation",
    "Adaptability",
    "Flexibility",
    "Time Management",
    "Prioritization",
    "Organization",
    "Attention to Detail",
    "Collaboration",
    "Teamwork",
    "Cross-Functional Collaboration",
    "Conflict Resolution",
    "Negotiation",
    "Emotional Intelligence",
    "Empathy",
    "Stakeholder Management",
    "Customer Focus",
    "Ownership",
    "Accountability",
    "Initiative",
    "Self-Motivation",
    "Work Ethic",
    "Resilience",
    "Growth Mindset",
    "Continuous Learning",
    "Curiosity",
    "Networking",
    "Relationship Building",
    "Cultural Awareness",
    "Remote Collaboration",
    "Facilitation",
    "Influencing",
    "Persuasion",
    "Multitasking",
    "Attention to Detail",
]

METHODOLOGIES = [
    "Object-Oriented Programming",
    "Functional Programming",
    "Reactive Programming",
    "Concurrent Programming",
    "Parallel Computing",
    "Algorithms",
    "Data Structures",
    "System Design",
    "Software Architecture",
    "API-First Development",
    "Refactoring",
    "Code Review",
    "Pair Programming",
    "Version Control",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Mercurial",
    "Trunk-Based Development",
    "Feature Flags",
    "Technical Documentation",
    "Technical Writing",
    "Debugging",
    "Profiling",
    "Performance Tuning",
    "Scalability",
    "Reliability",
    "Maintainability",
    "Internationalization",
    "Localization",
    "Open Source",
    "Agile Methodologies",
]

CERTS = [
    "AWS Certified Solutions Architect",
    "AWS Certified Developer",
    "AWS Certified SysOps Administrator",
    "AWS Certified DevOps Engineer",
    "Google Cloud Professional Cloud Architect",
    "Google Cloud Professional Data Engineer",
    "Microsoft Certified Azure Administrator",
    "Microsoft Certified Azure Solutions Architect",
    "Certified Kubernetes Administrator",
    "Certified Kubernetes Application Developer",
    "CISSP",
    "CISM",
    "CISA",
    "CompTIA Security+",
    "CompTIA Network+",
    "CEH",
    "PMP",
    "Certified ScrumMaster",
    "Professional Scrum Master",
    "SAFe Agilist",
    "Six Sigma Green Belt",
    "Six Sigma Black Belt",
    "ITIL",
    "Chartered Accountant",
    "CFA",
    "CPA",
    "FRM",
    "ACCA",
    "Company Secretary",
    "Cost Accountant",
    "Google Analytics Certification",
    "HubSpot Inbound Certification",
    "Salesforce Administrator",
    "Salesforce Developer",
    "TOGAF",
    "Tableau Desktop Specialist",
]

# ── Deep expansion (toward ~2000) ──────────────────────────────────────────────
CLOUD_EXTRA = [
    "AWS CloudTrail",
    "AWS Config",
    "AWS Organizations",
    "AWS Control Tower",
    "AWS Cost Explorer",
    "AWS WAF",
    "AWS Shield",
    "AWS GuardDuty",
    "AWS KMS",
    "AWS Cognito",
    "AWS AppSync",
    "AWS Amplify",
    "AWS EventBridge",
    "AWS Batch",
    "AWS CodePipeline",
    "AWS CodeBuild",
    "AWS CodeDeploy",
    "AWS CodeCommit",
    "AWS Elastic Load Balancing",
    "AWS Auto Scaling",
    "Amazon EMR",
    "Amazon QuickSight",
    "Amazon Comprehend",
    "Amazon Rekognition",
    "Amazon Textract",
    "Amazon Polly",
    "Amazon Transcribe",
    "Amazon Bedrock",
    "Amazon OpenSearch Service",
    "Amazon MSK",
    "Amazon Neptune",
    "Amazon DocumentDB",
    "Amazon Lightsail",
    "AWS Glue",
    "Azure Logic Apps",
    "Azure Service Bus",
    "Azure Event Hubs",
    "Azure Monitor",
    "Azure Application Insights",
    "Azure Key Vault",
    "Azure Container Apps",
    "Azure Container Registry",
    "Azure Data Lake",
    "Azure Databricks",
    "Azure ML",
    "Azure Cognitive Services",
    "Azure OpenAI Service",
    "Azure Functions",
    "Google Cloud Bigtable",
    "Google Cloud Composer",
    "Google Cloud Dataproc",
    "Google Cloud Looker",
    "Google Cloud Vision API",
    "Google Cloud Vertex AI",
    "Google Cloud Anthos",
    "Google Cloud Firestore",
    "Google Cloud IAM",
    "Cloudflare Pages",
    "Cloudflare R2",
    "Cloudflare CDN",
    "AWS Direct Connect",
]
FRAMEWORKS_EXTRA = [
    "Apache Struts",
    "JSF",
    "Vaadin",
    "Wicket",
    "Dropwizard",
    "Ktor",
    "http4k",
    "Rocket",
    "Axum",
    "Warp",
    "Tide",
    "Revel",
    "Beego",
    "Buffalo",
    "Slim",
    "CakePHP",
    "Yii",
    "Phalcon",
    "Zend Framework",
    "Hapi.js",
    "Sails.js",
    "AdonisJS",
    "LoopBack",
    "Meteor",
    "Feathers.js",
    "tRPC",
    "Hono",
    "SolidJS",
    "Qwik",
    "Preact",
    "Lit",
    "Stencil",
    "Vue Router",
    "Pinia",
    "Vuex",
    "NgRx",
    "Apollo Client",
    "Apollo Server",
    "Relay",
    "TanStack Query",
    "SWR",
    "React Hook Form",
    "Formik",
    "Zod",
    "Yup",
    "Joi",
    "Pydantic",
    "SQLAlchemy",
    "Alembic",
    "Celery",
    "Prisma",
    "Drizzle ORM",
    "TypeORM",
    "Sequelize",
    "Mongoose",
    "Knex.js",
    "Flyway",
    "Liquibase",
    "MyBatis",
    "jOOQ",
    "GORM",
    "Diesel",
    "Tortoise ORM",
    "Peewee",
    "Doctrine",
    "Eloquent",
    "ActiveRecord",
]
DATA_EXTRA = [
    "Snowflake Snowpark",
    "dbt Cloud",
    "Fivetran",
    "Stitch",
    "Airbyte",
    "Matillion",
    "Talend",
    "Informatica",
    "Apache NiFi",
    "Luigi",
    "Dagster",
    "Prefect",
    "Great Expectations",
    "Soda",
    "Monte Carlo",
    "Apache Iceberg",
    "Delta Lake",
    "Apache Hudi",
    "Parquet",
    "Avro",
    "Protocol Buffers",
    "Apache Arrow",
    "DuckDB",
    "Polars",
    "Dask",
    "Modin",
    "Vaex",
    "RAPIDS",
    "Numba",
    "Cython",
    "Statsmodels",
    "Prophet",
    "H2O.ai",
    "DataRobot",
    "Alteryx",
    "KNIME",
    "RapidMiner",
    "SAS",
    "SPSS",
    "Stata",
    "Google Data Studio",
    "Mode Analytics",
    "Sigma Computing",
    "Hex",
    "Census",
    "Hightouch",
    "Segment",
    "RudderStack",
    "Snowplow",
    "Heap",
    "PostHog",
    "Pendo",
    "FullStory",
    "Hotjar",
    "Optimizely",
    "VWO",
    "LaunchDarkly",
    "Split.io",
    "GrowthBook",
    "Cohort Analysis",
    "Funnel Analysis",
    "Retention Analysis",
    "Churn Prediction",
    "Customer Lifetime Value",
    "Market Basket Analysis",
    "Sentiment Analysis",
    "Topic Modeling",
    "Named Entity Recognition",
    "Speech Recognition",
    "Image Segmentation",
    "Object Detection",
    "OCR",
    "Knowledge Graphs",
    "Graph Neural Networks",
    "Transformers",
    "Diffusion Models",
    "GANs",
    "Transfer Learning",
    "Active Learning",
    "Federated Learning",
    "Model Quantization",
    "Model Distillation",
    "Hyperparameter Tuning",
    "AutoML",
    "Vector Embeddings",
    "Cosine Similarity",
    "Approximate Nearest Neighbors",
    "FAISS",
    "Annoy",
    "ScaNN",
    "LangGraph",
    "Haystack",
    "Semantic Kernel",
    "Guardrails",
    "Evaluation Frameworks",
    "RLHF",
    "Chain-of-Thought Prompting",
]
DEVOPS_EXTRA = [
    "Crossplane",
    "Kustomize",
    "Tilt",
    "Skaffold",
    "Buildpacks",
    "Kaniko",
    "Harbor",
    "Artifactory",
    "Nexus Repository",
    "SonarQube",
    "Snyk",
    "Trivy",
    "Falco",
    "OPA",
    "Open Policy Agent",
    "Kyverno",
    "Cilium",
    "Calico",
    "Rancher",
    "OpenShift",
    "Nomad",
    "Mesos",
    "CloudFormation",
    "AWS SAM",
    "Serverless Framework",
    "Knative",
    "KEDA",
    "Karpenter",
    "Cluster Autoscaler",
    "Velero",
    "etcd",
    "CoreDNS",
    "MetalLB",
    "Traefik",
    "Caddy",
    "Kong",
    "Tyk",
    "Apigee",
    "WSO2",
    "Thanos",
    "Cortex",
    "Loki",
    "Tempo",
    "Mimir",
    "VictoriaMetrics",
    "StatsD",
    "Telegraf",
    "Vector",
    "Graylog",
    "Honeycomb",
    "Lightstep",
    "Dynatrace",
    "AppDynamics",
    "Instana",
    "Rollbar",
    "Bugsnag",
    "Runbook Automation",
    "Chaos Monkey",
    "Gremlin",
    "Litmus",
    "Performance Engineering",
]
SECURITY_EXTRA = [
    "Identity Federation",
    "Single Sign-On",
    "Multi-Factor Authentication",
    "Privileged Access Management",
    "Secrets Management",
    "Certificate Management",
    "Web Application Firewall",
    "DDoS Mitigation",
    "Intrusion Detection",
    "Security Information and Event Management",
    "Threat Intelligence",
    "Threat Hunting",
    "Vulnerability Management",
    "Patch Management",
    "Security Hardening",
    "Network Segmentation",
    "Zero Trust Architecture",
    "Cloud Security Posture Management",
    "Container Scanning",
    "Dependency Scanning",
    "Software Composition Analysis",
    "Secure SDLC",
    "Security Champions",
    "Tabletop Exercises",
    "Forensic Analysis",
    "Reverse Engineering",
    "Exploit Development",
    "Social Engineering",
    "Phishing Simulation",
    "Nessus",
    "Qualys",
    "Snort",
    "Suricata",
    "OSSEC",
    "Cobalt Strike",
    "Aircrack-ng",
    "John the Ripper",
    "Hashcat",
    "OWASP ZAP",
    "Checkmarx",
    "Veracode",
    "Semgrep",
    "HashiCorp Vault",
    "CyberArk",
    "Okta",
    "Auth0",
    "Keycloak",
    "Ping Identity",
]
PRODUCT_BIZ = [
    "Business Analysis",
    "Business Strategy",
    "Corporate Strategy",
    "Management Consulting",
    "Strategy Consulting",
    "Operations Strategy",
    "Go-to-Market Planning",
    "Pricing Strategy",
    "Monetization",
    "Subscription Models",
    "Freemium Strategy",
    "Partnership Development",
    "Strategic Partnerships",
    "Vendor Negotiation",
    "Contract Management",
    "Procurement Strategy",
    "P&L Management",
    "Revenue Growth",
    "Cost Optimization",
    "Business Process Mapping",
    "Process Reengineering",
    "Workflow Automation",
    "RPA",
    "UiPath",
    "Automation Anywhere",
    "Blue Prism",
    "Power Automate",
    "Zapier",
    "Make",
    "n8n",
    "Low-Code Development",
    "No-Code Development",
    "Bubble",
    "Webflow",
    "Retool",
    "Airtable",
    "Smartsheet",
    "ClickUp",
    "Requirements Analysis",
    "Gap Analysis",
    "SWOT Analysis",
    "Cost-Benefit Analysis",
    "Feasibility Analysis",
    "Business Case Development",
    "Stakeholder Analysis",
    "KPI Definition",
    "Metrics Design",
    "North Star Metric",
    "Business Modeling",
    "Financial Forecasting",
    "Scenario Planning",
    "Market Sizing",
    "TAM SAM SOM",
    "User Acquisition",
    "Activation",
    "Retention Strategy",
    "Referral Programs",
    "Loyalty Programs",
    "Customer Onboarding",
    "Customer Success Management",
    "Net Promoter Score",
    "Voice of Customer",
    "Customer Journey Mapping",
]
INDUSTRY_EXTRA = [
    "FinTech",
    "HealthTech",
    "EdTech",
    "AgriTech",
    "PropTech",
    "InsurTech",
    "LegalTech",
    "RetailTech",
    "FoodTech",
    "CleanTech",
    "DeepTech",
    "SpaceTech",
    "Gaming",
    "Game Development",
    "Unity",
    "Unreal Engine",
    "Godot",
    "Game Design",
    "Level Design",
    "AR/VR",
    "Augmented Reality",
    "Virtual Reality",
    "Mixed Reality",
    "Metaverse",
    "NFTs",
    "Web3",
    "Smart Contracts",
    "Ethereum",
    "Hyperledger",
    "Solana",
    "Polygon",
    "Blockchain Development",
    "Decentralized Finance",
    "Telecom",
    "5G",
    "VoIP",
    "SDN",
    "Network Function Virtualization",
    "Banking",
    "Capital Markets",
    "Asset Management",
    "Wealth Management",
    "Payments Processing",
    "UPI",
    "Digital Wallets",
    "Lending",
    "Mortgage",
    "Claims Processing",
    "Underwriting",
    "Reinsurance",
    "Risk Modeling",
    "Clinical Trials",
    "Regulatory Affairs",
    "Drug Safety",
    "Bioinformatics",
    "Genomics",
    "Medical Devices",
    "Telemedicine",
    "Electronic Health Records",
    "HL7",
    "FHIR",
    "Hospital Management",
    "Pharmaceutical Sales",
    "Supply Chain Analytics",
    "Logistics Optimization",
    "Fleet Management",
    "Last-Mile Delivery",
    "Cold Chain",
    "Customs Compliance",
    "Import Export",
    "Manufacturing Execution Systems",
    "Industrial Automation",
    "SCADA",
    "Predictive Maintenance",
    "Digital Twin",
    "Computer-Aided Manufacturing",
    "Lean Manufacturing",
    "Total Quality Management",
    "ISO 9001",
    "Kanban Manufacturing",
    "Renewable Energy",
    "Solar Energy",
    "Wind Energy",
    "Energy Storage",
    "Smart Grid",
    "Sustainability",
    "ESG",
    "Carbon Accounting",
    "Circular Economy",
]
CREATIVE_EXTRA = [
    "Video Editing",
    "Video Production",
    "Videography",
    "Photography",
    "Photo Editing",
    "Color Grading",
    "Sound Design",
    "Audio Editing",
    "Music Production",
    "Podcast Production",
    "Animation",
    "2D Animation",
    "3D Animation",
    "Motion Graphics",
    "VFX",
    "Compositing",
    "Storyboarding",
    "Scriptwriting",
    "Creative Direction",
    "Art Direction",
    "Content Creation",
    "Social Media Content",
    "Reels Production",
    "YouTube Production",
    "DaVinci Resolve",
    "Final Cut Pro",
    "Adobe Lightroom",
    "CapCut",
    "Procreate",
    "Webcomics",
    "Editorial Design",
    "Print Design",
    "Packaging Design",
    "Environmental Graphics",
]
WRITING_EXTRA = [
    "Content Writing",
    "Copywriting",
    "Technical Writing",
    "UX Writing",
    "Creative Writing",
    "Ghostwriting",
    "Editing",
    "Proofreading",
    "Journalism",
    "Blogging",
    "SEO Writing",
    "Grant Writing",
    "Proposal Writing",
    "Report Writing",
    "Business Writing",
    "Email Copywriting",
    "Sales Copywriting",
    "Script Writing",
    "Localization",
    "Translation",
    "Transcreation",
    "Documentation",
    "Knowledge Base Management",
    "Style Guide Development",
    "Content Editing",
]
COLLAB_TOOLS = [
    "Slack",
    "Microsoft Teams",
    "Zoom",
    "Google Workspace",
    "Microsoft Office",
    "Microsoft Word",
    "Microsoft PowerPoint",
    "Microsoft Outlook",
    "Google Docs",
    "Google Slides",
    "Loom",
    "Calendly",
    "DocuSign",
    "Coda",
    "Obsidian",
    "Roam Research",
    "Whimsical",
    "Lucidchart",
    "draw.io",
    "Excalidraw",
    "Mural",
    "FigJam",
    "Basecamp",
    "Wrike",
    "Teamwork",
    "Height",
    "Shortcut",
    "Azure Boards",
    "YouTrack",
    "Redmine",
    "ServiceNow",
    "Jira Service Management",
]
SOFT_EXTRA = [
    "Cross-Cultural Communication",
    "Executive Presence",
    "Boardroom Communication",
    "Negotiation Tactics",
    "Persuasive Communication",
    "Diplomacy",
    "Tact",
    "Patience",
    "Perseverance",
    "Self-Awareness",
    "Self-Regulation",
    "Motivation",
    "Goal Setting",
    "Prioritization Skills",
    "Workload Management",
    "Stress Management",
    "Work-Life Balance",
    "Remote Work",
    "Asynchronous Communication",
    "Documentation Discipline",
    "Knowledge Sharing",
    "Onboarding New Team Members",
    "Performance Feedback",
    "Giving Feedback",
    "Receiving Feedback",
    "Conflict Mediation",
    "Consensus Building",
    "Change Leadership",
    "Vision Setting",
    "Strategic Planning",
    "Execution Excellence",
    "Bias for Action",
    "First-Principles Thinking",
    "Systems Thinking",
    "Design Thinking",
    "Lateral Thinking",
    "Root Cause Analysis",
    "Data-Driven Decision Making",
    "Customer Empathy",
    "Commercial Awareness",
    "Business Acumen",
    "Entrepreneurship",
    "Intrapreneurship",
    "Resourcefulness",
    "Attention to Quality",
    "Reliability",
]
CERTS_EXTRA = [
    "Google Cloud Associate Cloud Engineer",
    "AWS Certified Cloud Practitioner",
    "AWS Certified Machine Learning",
    "AWS Certified Security",
    "AWS Certified Data Analytics",
    "Microsoft Certified Azure Developer",
    "Microsoft Certified Azure Data Engineer",
    "Microsoft Certified Power BI Data Analyst",
    "Certified Kubernetes Security Specialist",
    "HashiCorp Certified Terraform Associate",
    "Docker Certified Associate",
    "Certified Information Privacy Professional",
    "CompTIA A+",
    "CompTIA Cloud+",
    "GIAC Security Essentials",
    "OSCP",
    "Certified Cloud Security Professional",
    "Professional Scrum Product Owner",
    "Certified Product Manager",
    "Pragmatic Marketing",
    "Lean Six Sigma Yellow Belt",
    "PRINCE2",
    "Certified Business Analysis Professional",
    "Google Ads Certification",
    "Meta Blueprint Certification",
    "Hootsuite Certification",
    "Salesforce Marketing Cloud Consultant",
    "Tableau Certified Data Analyst",
    "Microsoft Certified Power Platform",
    "SnowPro Core",
    "Databricks Certified Data Engineer",
    "Certified Analytics Professional",
    "Financial Risk Manager",
    "Chartered Financial Analyst",
]

GAP_FILL = [
    # More languages / runtimes
    "Nim",
    "V",
    "Ballerina",
    "PureScript",
    "ReasonML",
    "ReScript",
    "CoffeeScript",
    "Hack",
    "PHP 8",
    "Java 17",
    "Java 21",
    "Python 3.12",
    "ES6",
    "WebAssembly Text",
    # More frontend
    "Headless UI",
    "Mantine",
    "DaisyUI",
    "Bulma",
    "Foundation",
    "Stimulus",
    "Turbo",
    "HTMX",
    "Web Sockets",
    "Server-Sent Events",
    "Service Workers",
    "IndexedDB",
    "Web Workers",
    "Canvas API",
    "SVG Animation",
    "Lottie",
    "Internationalization (i18n)",
    "Micro-interactions",
    "Atomic Design",
    # More backend / arch
    "Hexagonal Architecture",
    "Onion Architecture",
    "Microkernel Architecture",
    "Saga Pattern",
    "Outbox Pattern",
    "Circuit Breaker",
    "Bulkhead Pattern",
    "Idempotency",
    "Backpressure",
    "Eventual Consistency",
    "Strong Consistency",
    "Distributed Transactions",
    "Two-Phase Commit",
    "Consensus Algorithms",
    "Raft",
    "Paxos",
    "Leader Election",
    "Service Discovery",
    "API Versioning",
    "Pagination",
    "Bulk APIs",
    "Batch Processing",
    "Job Scheduling",
    "Quartz",
    # More databases / data
    "Materialized Views",
    "Stored Procedures",
    "Triggers",
    "Partitioning",
    "Database Normalization",
    "Denormalization",
    "Schema Design",
    "Data Cataloging",
    "Data Lineage",
    "Reverse ETL",
    "Change Data Capture",
    "Debezium",
    "Kafka Connect",
    "Kafka Streams",
    "ksqlDB",
    "Pulsar",
    "RabbitMQ",
    "ActiveMQ",
    "NATS",
    "ZeroMQ",
    "Amazon SQS",
    "Celery Beat",
    # More cloud / platform
    "Terraform Cloud",
    "Atlantis",
    "Infracost",
    "AWS Well-Architected",
    "Landing Zones",
    "Account Vending",
    "Service Catalogs",
    "Cost Allocation Tags",
    "Reserved Instances",
    "Spot Instances",
    "Savings Plans",
    "Edge Computing",
    "CDN Configuration",
    "Anycast",
    "Global Load Balancing",
    # More ML / AI
    "Feature Stores",
    "Feast",
    "Model Registry",
    "Model Cards",
    "Drift Detection",
    "Explainable AI",
    "SHAP",
    "LIME",
    "Fairness in ML",
    "Responsible AI",
    "Synthetic Data",
    "Data Augmentation",
    "Self-Supervised Learning",
    "Few-Shot Learning",
    "Zero-Shot Learning",
    "Multimodal Models",
    "Speech Synthesis",
    "Text-to-Speech",
    "Speech-to-Text",
    "Whisper",
    "Stable Diffusion",
    "Midjourney",
    "DALL-E",
    "Agentic AI",
    "AI Agents",
    "Tool Use",
    "Function Calling",
    "Context Engineering",
    "Eval Harnesses",
    # More marketing / growth
    "Marketing Mix Modeling",
    "Media Buying",
    "Creative Testing",
    "UGC",
    "Community-Led Growth",
    "Product-Led Growth",
    "SEO Audits",
    "Schema Markup",
    "Local SEO",
    "International SEO",
    "App Store Optimization",
    "Push Marketing",
    "SMS Marketing",
    "Push Notifications",
    "Customer Data Platforms",
    "CDP",
    "Lifecycle Campaigns",
    "Win-Back Campaigns",
    "Loyalty Marketing",
    "Brand Positioning",
    "Naming",
    "Tagline Development",
    "PR Outreach",
    "Press Releases",
    "Thought Leadership",
    "Webinar Marketing",
    "Field Marketing",
    "Partner Marketing",
    "Co-Marketing",
    "Event Sponsorship",
    "Trade Shows",
    # More sales / CS
    "MEDDIC",
    "MEDDPICC",
    "SPIN Selling",
    "Challenger Sale",
    "BANT",
    "Sales Playbooks",
    "Discovery Calls",
    "Demo Delivery",
    "Proof of Concept",
    "RFP Response",
    "Proposal Development",
    "Deal Desk",
    "Sales Compensation",
    "Renewals Management",
    "Expansion Revenue",
    "Net Revenue Retention",
    "Customer Health Scoring",
    "QBRs",
    "Escalation Management",
    # More finance
    "Revenue Recognition",
    "ARR",
    "MRR",
    "Burn Rate",
    "Runway Analysis",
    "Variance Analysis",
    "Cohort Economics",
    "LTV/CAC",
    "Scenario Modeling",
    "Three-Statement Modeling",
    "LBO Modeling",
    "Comparable Company Analysis",
    "Due Diligence",
    "Financial Due Diligence",
    "Capital Budgeting",
    "Hedging",
    "Derivatives",
    "Fixed Income",
    "Equities",
    "Forex",
    "Commodities Trading",
    "Algorithmic Trading",
    "Quantitative Analysis",
    "Credit Risk Modeling",
    "Fraud Detection",
    "AML",
    "KYC",
    "Regulatory Reporting",
    "Basel III",
    # More HR / ops
    "Headcount Planning",
    "Compensation Benchmarking",
    "Equity Compensation",
    "Total Rewards",
    "Employee Lifecycle",
    "Exit Interviews",
    "Retention Programs",
    "Culture Building",
    "Remote Team Management",
    "Distributed Teams",
    "Vendor Onboarding",
    "SLA Management",
    "Capacity Management",
    "Demand Forecasting",
    "S&OP",
    "Inventory Optimization",
    "Reverse Logistics",
    "Order Management",
    # More tools
    "Postman",
    "Insomnia",
    "Bruno",
    "DBeaver",
    "TablePlus",
    "pgAdmin",
    "DataGrip",
    "VS Code",
    "IntelliJ IDEA",
    "PyCharm",
    "WebStorm",
    "Vim",
    "Neovim",
    "Emacs",
    "Sublime Text",
    "Cursor",
    "GitHub Copilot",
    "Xcode",
    "Android Studio",
    "Eclipse",
    "Visual Studio",
    "Jupyter Notebook",
    "Google Colab",
    "Databricks Notebooks",
    "Observable",
    "Hoppscotch",
    "Charles Proxy",
    "Fiddler",
    # More PM / analytics
    "Roadmap Communication",
    "Release Notes",
    "Beta Programs",
    "Feature Flagging",
    "Experiment Design",
    "Statistical Significance",
    "Bayesian A/B Testing",
    "North Star Frameworks",
    "RICE Prioritization",
    "Kano Model",
    "MoSCoW",
    "Story Mapping",
    "Impact Mapping",
    "Opportunity Solution Trees",
    "Continuous Discovery",
    "Dual-Track Agile",
    "Outcome-Based Roadmaps",
]

CATEGORIES = [
    LANGUAGES,
    FRONTEND,
    BACKEND,
    DATABASES,
    CLOUD,
    DEVOPS,
    DATA_ML,
    MOBILE,
    TESTING,
    SECURITY,
    DESIGN,
    PM_AGILE,
    MARKETING,
    SALES,
    FINANCE,
    HR,
    OPS_INDUSTRY,
    SOFT_SKILLS,
    METHODOLOGIES,
    CERTS,
    CLOUD_EXTRA,
    FRAMEWORKS_EXTRA,
    DATA_EXTRA,
    DEVOPS_EXTRA,
    SECURITY_EXTRA,
    PRODUCT_BIZ,
    INDUSTRY_EXTRA,
    CREATIVE_EXTRA,
    WRITING_EXTRA,
    COLLAB_TOOLS,
    SOFT_EXTRA,
    CERTS_EXTRA,
    GAP_FILL,
]

# ── Aliases: variant (any case/punctuation) → canonical display label ───────────
ALIASES = {
    "reactjs": "React",
    "react.js": "React",
    "js": "JavaScript",
    "ecmascript": "JavaScript",
    "ts": "TypeScript",
    "nextjs": "Next.js",
    "next js": "Next.js",
    "vuejs": "Vue.js",
    "vue": "Vue.js",
    "nuxtjs": "Nuxt.js",
    "nuxt": "Nuxt.js",
    "angularjs": "Angular",
    "node": "Node.js",
    "nodejs": "Node.js",
    "node js": "Node.js",
    "expressjs": "Express.js",
    "express": "Express.js",
    "tailwind": "Tailwind CSS",
    "tailwindcss": "Tailwind CSS",
    "py": "Python",
    "python3": "Python",
    "golang": "Go",
    "k8s": "Kubernetes",
    "postgres": "PostgreSQL",
    "postgresql": "PostgreSQL",
    "psql": "PostgreSQL",
    "mongo": "MongoDB",
    "es": "Elasticsearch",
    "gcp": "Google Cloud Platform",
    "google cloud": "Google Cloud Platform",
    "gcloud": "Google Cloud Platform",
    "aws cloud": "AWS",
    "amazon web services": "AWS",
    "azure": "Microsoft Azure",
    "ms azure": "Microsoft Azure",
    "ci cd": "CI/CD",
    "cicd": "CI/CD",
    "rest api": "REST APIs",
    "restful api": "REST APIs",
    "restful apis": "REST APIs",
    "rest apis": "REST APIs",
    "restful services": "REST APIs",
    "rest": "REST APIs",
    "ml": "Machine Learning",
    "ai": "Generative AI",
    "genai": "Generative AI",
    "gen ai": "Generative AI",
    "dl": "Deep Learning",
    "nlp": "Natural Language Processing",
    "llm": "Large Language Models",
    "llms": "Large Language Models",
    "rag": "RAG",
    "sklearn": "scikit-learn",
    "scikit learn": "scikit-learn",
    "tf": "TensorFlow",
    "pytorch": "PyTorch",
    "k8": "Kubernetes",
    "gha": "GitHub Actions",
    "github actions": "GitHub Actions",
    "tf iac": "Terraform",
    "iac": "Infrastructure as Code",
    "sre": "Site Reliability Engineering",
    "pm": "Product Management",
    "product manager": "Product Management",
    "ux": "UX Design",
    "ui": "UI Design",
    "ui ux": "UI Design",
    "ui/ux": "UI Design",
    "qa": "Quality Assurance",
    "tdd": "Test-Driven Development",
    "bdd": "Behavior-Driven Development",
    "oop": "Object-Oriented Programming",
    "seo": "SEO",
    "sem": "SEM",
    "ppc": "PPC",
    "cro": "Conversion Rate Optimization",
    "abm": "Account-Based Marketing",
    "crm": "CRM",
    "ga": "Google Analytics",
    "ga4": "GA4",
    "gtm": "Google Tag Manager",
    "fpa": "FP&A",
    "fp&a": "FP&A",
    "ca": "Chartered Accountant",
    "m&a": "Mergers and Acquisitions",
    "mna": "Mergers and Acquisitions",
    "vc": "Venture Capital",
    "pe": "Private Equity",
    "spring boot": "Spring Boot",
    "springboot": "Spring Boot",
    "dotnet": ".NET",
    ".net core": ".NET Core",
    "fast api": "FastAPI",
    "fastapi": "FastAPI",
    "postgre": "PostgreSQL",
    "mssql": "Microsoft SQL Server",
    "sql server": "Microsoft SQL Server",
    "bigquery": "Google BigQuery",
    "redshift": "Amazon Redshift",
    "s3": "Amazon S3",
    "ec2": "Amazon EC2",
    "lambda": "AWS Lambda",
    "eks": "Amazon EKS",
    "ecs": "Amazon ECS",
    "gke": "Google Kubernetes Engine",
    "aks": "Azure Kubernetes Service",
    "apache kafka": "Apache Kafka",
    "kafka": "Apache Kafka",
    "spark": "Apache Spark",
    "pyspark": "PySpark",
    "airflow": "Apache Airflow",
    "powerbi": "Power BI",
    "power bi": "Power BI",
    "data viz": "Data Visualization",
    "viz": "Data Visualization",
    "a/b testing": "A/B Testing",
    "ab testing": "A/B Testing",
    "k8s admin": "Kubernetes",
    "rn": "React Native",
    "react native": "React Native",
    "swiftui": "SwiftUI",
    "jetpack compose": "Jetpack Compose",
    "objective c": "Objective-C",
    "c sharp": "C#",
    "csharp": "C#",
    "cpp": "C++",
    "c plus plus": "C++",
    "html5": "HTML",
    "css3": "CSS",
    "scss": "Sass",
    "sass/scss": "Sass",
    "communication skills": "Communication",
    "leadership skills": "Leadership",
    "problem-solving": "Problem Solving",
    "problem solving": "Problem Solving",
    "team work": "Teamwork",
    "team-work": "Teamwork",
    "time-management": "Time Management",
    "stakeholder mgmt": "Stakeholder Management",
    "ms excel": "Excel",
    "microsoft excel": "Excel",
    "advanced excel": "Advanced Excel",
    "g sheets": "Google Sheets",
    "salesforce crm": "Salesforce",
    "hubspot": "HubSpot",
    "ms sql": "Microsoft SQL Server",
    "rest-ful": "REST APIs",
    "graph ql": "GraphQL",
    "graphql api": "GraphQL",
    "micro services": "Microservices",
    "micro-services": "Microservices",
    "event driven architecture": "Event-Driven Architecture",
    "distributed system": "Distributed Systems",
    "system-design": "System Design",
    "data structures and algorithms": "Data Structures",
    "dsa": "Data Structures",
}


def _norm(s: str) -> str:
    return re.sub(r"[^a-z0-9+#]", "", s.lower().strip())


def main() -> None:
    # Dedupe display labels by normalized token (first label wins).
    seen: dict[str, str] = {}
    for cat in CATEGORIES:
        for label in cat:
            key = _norm(label)
            if key and key not in seen:
                seen[key] = label
    skills = sorted(seen.values(), key=str.lower)

    # Keep only aliases whose canonical exists in the vocab (by normalized token).
    canon_norms = set(seen)
    aliases = {}
    for variant, canon in ALIASES.items():
        if _norm(canon) in canon_norms or _norm(variant) != _norm(canon):
            aliases[variant] = canon

    out = Path(__file__).resolve().parents[1] / "src/hireloop_api/data/skills_vocab.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps({"skills": skills, "aliases": aliases}, ensure_ascii=False, indent=0),
        encoding="utf-8",
    )
    print(f"skills: {len(skills)}  aliases: {len(aliases)}  -> {out}")


if __name__ == "__main__":
    main()
